### ISSUE TITLE
Memory leak starting at line 39

### ISSUE THREAD

**Issue by ghost** [rifkybujana/Learn-OpenGL#1]
You probably haven't cared about this project in ages, but I just wanted to offer some advice.
Either don't use `new` (which you *shouldn't* do here as it is unnecessary) or `delete` your pointers when you no longer need them.

**Comment by rifkybujana** [comment]
Thank you so much for your advice, i really apreciate it

**Comment by ghost** [comment]
You're welcome lad 👍
